[project]
name = "agent-bricks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faker>=40.4.0",
    "pydantic[standard]>=2.12.5",
]
